{% set jupyterlab_version = ">=3.5.3,<3.6" %}
{% set version = "0.0.10" %}
{% set jupyterlab_version = ">=3.5.3,<3.6" %}

package:
  name: jupyterlite-pyodide-kernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlite-pyodide-kernel/jupyterlite_pyodide_kernel-{{ version }}.tar.gz
  sha256: 747b8174109e7d9cae71765c4e72a8cf98dd62cc0eca07a2bd06e7f40d502f19

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - jupyter-piplite = jupyterlite_pyodide_kernel.app:main

requirements:
  host:
    - hatchling >=1.4.0
    - jupyterlab {{ jupyterlab_version }}
    - pip
    - python >=3.8
  run:
    - jupyterlite-core >=0.1.0,<0.2.0
    - pkginfo
    - python >=3.8

test:
  imports:
    - jupyterlite_pyodide_kernel
  commands:
    - pip check
    - jupyter piplite --version
    - jupyter-piplite --help
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyterlite/pyodide-kernel-extension.*v{{ version.replace('.', '\.') }}.*OK" labextensions
    - jupyter lite build
    - grep -iE "pyodide-kernel-extension" _output/jupyter-lite.json
  requires:
    - jupyterlab {{ jupyterlab_version }}
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/jupyterlite/pyodide-kernel
  summary: Python kernel for JupyterLite powered by Pyodide
  doc_url: https://jupyterlite-pyodide-kernel.rtfd.io
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlite_pyodide_kernel/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
