{% set version = "0.5.0b0" %}

{% set python_min = python_min | default("3.9") %}

{% set js_version = version.replace("a", "-alpha.").replace("b", "-beta.").replace("rc", "-rc.") %}

# the if prevents bot duplicates
{% if 1 %}{% set jupyterlab_version = ">=4.3.3,<4.4.0" %}{% endif %}

package:
  name: jupyterlite-pyodide-kernel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlite-pyodide-kernel/jupyterlite_pyodide_kernel-{{ version }}.tar.gz
  sha256: c60b0bbacf4de4b0d3ff960c7cdec1bc6c3ef094fefc53b7f5a2c4e50f27f2dd

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - jupyter-piplite = jupyterlite_pyodide_kernel.app:main

requirements:
  host:
    - hatchling >=1.4.0
    - jupyterlab {{ jupyterlab_version }}
    - pip
    - python {{ python_min }}
  run:
    - jupyterlite-core >=0.5.0b0,<0.6.0
    - pkginfo
    - python >={{ python_min }}

test:
  imports:
    - jupyterlite_pyodide_kernel
  requires:
    - jupyterlab {{ jupyterlab_version }}
    - pip
    - python {{ python_min }}
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter piplite --version
    - jupyter-piplite --help
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyterlite/pyodide-kernel-extension.*v{{ js_version.replace('.', '\.') }}.*OK" labextensions
    - jupyter lite build
    - grep -iE "pyodide-kernel-extension" _output/jupyter-lite.json

about:
  home: https://github.com/jupyterlite/pyodide-kernel
  summary: Python kernel for JupyterLite powered by Pyodide
  doc_url: https://jupyterlite-pyodide-kernel.rtfd.io
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlite_pyodide_kernel/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
