# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.7.0a4"
  jupyterlab_min: "4.5.0b0"
  jupyterlab_max: "4.6.0"
  jupyterlite_core_min: "0.7.0a7"
  jupyterlite_core_max: "0.8.0"
  # derived
  js_version: ${{ version | replace("a", "-alpha.") | replace("b", "-beta.") | replace("rc", "-rc.") }}


package:
  name: jupyterlite-pyodide-kernel
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlite-pyodide-kernel/jupyterlite_pyodide_kernel-${{ version }}.tar.gz
  sha256: 0e546c7a57238be97840a4e162797eb4de89515382e432eae053a13539ed1b6c

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter-piplite = jupyterlite_pyodide_kernel.app:main

requirements:
  host:
    - hatchling >=1.4.0
    - jupyterlab ${{ jupyterlab_min }}.*
    - pip
    - python ${{ python_min }}.*
  run:
    - jupyterlite-core >=${{ jupyterlite_core_min }}
    - pkginfo
    - python >=${{ python_min }}

tests:
  - python:
      imports: jupyterlite_pyodide_kernel
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - jupyterlab ${{ jupyterlab_min }}.*
        - jupyterlite-core ${{ jupyterlite_core_min }}.*
        - python ${{ python_min }}.*
    script:
      - jupyter piplite --version
      - jupyter-piplite --help
      - jupyter labextension list
      - jupyter labextension list 2>&1 | python -c "import re, sys; assert re.search(r'@jupyterlite/pyodide-kernel-extension.*v${{ js_version | replace(".", "\\.") }}.*OK', sys.stdin.read())"
      - jupyter lite build
      - python -c "from pathlib import Path; assert b'pyodide-kernel-extension' in Path('_output/jupyter-lite.json').read_bytes()"

about:
  summary: Python kernel for JupyterLite powered by Pyodide
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlite_pyodide_kernel/labextension/static/third-party-licenses.json
  homepage: https://github.com/jupyterlite/pyodide-kernel
  documentation: https://jupyterlite-pyodide-kernel.rtfd.io

extra:
  recipe-maintainers:
    - agriyakhetarpal
    - bollwyvl
    - jtpio
    - martinRenou
